[package]
name = "rust_container"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[example]]
name = "hello_world"
path = "examples/hello_world/hello_world.rs"